version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      serialport:
        patterns:
          - 'serialport'
          - '@serialport/*'
      mui:
        patterns:
          - '@mui/*'
      aws:
        patterns:
          - '@aws-sdk/*'
    open-pull-requests-limit: 20
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
