# for development purposes
version: '3.8'
services:
  mariadb:
    image: mariadb:10.5
    volumes:
      - mysql_data:/var/lib/mysql
    command: >-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=sensor_data_collection
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  backend:
    image: node:14
    env_file: .env
    volumes:
      - .:/opt/app:delegated
    working_dir: /opt/app
    command: npx lerna run dev --stream --scope=sdc2-server
    ports:
      - 4000:4000
    depends_on:
      - mariadb
  frontend:
    image: node:14
    volumes:
      - .:/opt/app:delegated
    working_dir: /opt/app
    command: npx lerna run start --stream --scope=sdc2-frontend
    ports:
      - 8080:3000
    depends_on:
      - backend
volumes:
  mysql_data:
