version: '3.7'
services:
  mariadb:
    image: mariadb:latest
    volumes:
      - mysql_data:/var/lib/mysql
      - ./packages/sdc2-server/db/init:/docker-entrypoint-initdb.d
    command: >-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=sensor_data_collection
      - MYSQL_USER=sensor_data_collection
      - MYSQL_PASSWORD=mysql-password
      - MYSQL_ROOT_PASSWORD=mysql-root-password
  backend:
    image: node:10
    volumes:
      - .:/opt/app:delegated
    working_dir: /opt/app
    command: npx lerna run dev --stream --scope=sdc2-server
    ports:
      - 4000:4000
    depends_on:
      - mariadb
  frontend:
    image: node:10
    volumes:
      - .:/opt/app:delegated
    working_dir: /opt/app
    command: npx lerna run serve --stream --scope=sdc2-frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
  bootstrap:
    image: node:10
    volumes:
      - .:/opt/app:delegated
    working_dir: /opt/app
    command: npx lerna bootstrap
  build:
    image: node:10
    volumes:
      - .:/opt/app:delegated
    working_dir: /opt/app
    command: npx lerna run build --stream --scope=sdc2-frontend
volumes:
  mysql_data:
