version: '3.8'
services:
  mariadb:
    image: mariadb:10.5
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./packages/sdc2-server/db/init:/docker-entrypoint-initdb.d
    command: >-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=sensor_data_collection
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    restart: unless-stopped
  server:
    image: ghcr.io/lpgera/sensor-data-collection:latest
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    depends_on:
      - mariadb
    restart: unless-stopped
